"""Added organizations

Revision ID: c2fcc7b7d903
Revises: 8ed764023388
Create Date: 2025-04-16 10:24:17.508013

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2fcc7b7d903'
down_revision: Union[str, None] = '8ed764023388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tokenblacklist_token', table_name='tokenblacklist')
    op.drop_table('tokenblacklist')
    op.add_column('organization', sa.Column('org_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_organization_stripe_customer_id', table_name='organization')
    op.create_index(op.f('ix_organization_org_url'), 'organization', ['org_url'], unique=False)
    op.drop_column('organization', 'stripe_subscription_id')
    op.drop_column('organization', 'stripe_customer_id')
    op.add_column('user', sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'user', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'organization_id')
    op.add_column('organization', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_organization_org_url'), table_name='organization')
    op.create_index('ix_organization_stripe_customer_id', 'organization', ['stripe_customer_id'], unique=False)
    op.drop_column('organization', 'org_url')
    op.create_table('tokenblacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tokenblacklist_pkey')
    )
    op.create_index('ix_tokenblacklist_token', 'tokenblacklist', ['token'], unique=True)
    # ### end Alembic commands ###
